export const data = [
  {
    id: 1,
    title: "Admin Panel",
    img: ["images/admin-panel-simple/2022-03-22 (43).png"],
    features: ["React", "StyledComponents"],
    url: "https://admin-app-table-simple.vercel.app/",
    github: "https://github.com/JohnKucharsky/admin-app-table-simple",
    color: false,
  },

  {
    id: 2,
    title: "Bootstrap",
    img: [
      "images/bootstrap-ninja/2022-03-22 (1).png",
      "images/bootstrap-ninja/2022-03-22 (2).png",
      "images/bootstrap-ninja/2022-03-22 (3).png",
      "images/bootstrap-ninja/2022-03-22 (4).png",
      "images/bootstrap-ninja/2022-03-22 (5).png",
    ],
    features: ["Bootstrap", "HTML", "CSS"],
    url: "https://bootstrap5-02.vercel.app/",
    github: "https://github.com/JohnKucharsky/Bootstrap5-02",
    color: false,
  },
  {
    id: 3,
    title: "Calculator Modal",
    img: ["images/calc-redux/2022-03-22 (30).png"],
    features: ["React", "ReduxToolkit", "Firebase"],
    url: "https://calcredux-ashen.vercel.app/",
    github: "https://github.com/JohnKucharsky/calcredux",
    color: false,
  },

  {
    id: 4,
    title: "Portfolio",
    img: [
      "images/egator-portfolio/2022-03-22 (37).png",
      "images/egator-portfolio/2022-03-22 (38).png",
      "images/egator-portfolio/2022-03-22 (39).png",
      "images/egator-portfolio/2022-03-22 (40).png",
      "images/egator-portfolio/2022-03-22 (41).png",
      "images/egator-portfolio/2022-03-22 (42).png",
    ],
    features: ["React", "CSS", "Animation"],
    url: "https://egator.vercel.app/",
    github: "https://github.com/JohnKucharsky/egator",
    color: true,
  },
  {
    id: 5,
    title: "Finn Flare",
    img: [
      "images/finn-flare/2022-03-22 (32).png",
      "images/finn-flare/2022-03-22 (33).png",
      "images/finn-flare/2022-03-22 (34).png",
      "images/finn-flare/2022-03-22 (35).png",
    ],
    features: ["React", "ReactRouter", "Contentful", "TailwindCSS"],
    url: "https://finn-flaree.vercel.app/",
    github: "https://github.com/JohnKucharsky/FinnFlare",
    color: true,
  },
  {
    id: 6,
    title: "Pixabay API",
    img: ["images/gallery/2022-03-22 (24).png"],
    features: ["React", "API", "TailwindCSS"],
    url: "https://finn-flaree.vercel.app/",
    github: "https://github.com/JohnKucharsky/FinnFlare",
    color: false,
  },
  {
    id: 7,
    title: "CSS Grid",
    img: ["images/grid/2022-03-22 (13).png", "images/grid/2022-03-22 (14).png"],
    features: ["HTML", "CSS", "Grid"],
    url: "https://inspiring-sammet-0cfd2b.netlify.app/",
    github: "https://github.com/JohnKucharsky/valid-input",
    color: false,
  },
  {
    id: 8,
    title: "Admin Panel 2",
    img: ["images/lama-admin-main/2022-03-22 (44).png"],
    features: ["React", "CSS", "Recharts"],
    url: "https://lama-admin-main.vercel.app/",
    github: "https://github.com/JohnKucharsky/Lama-Admin-main",
    color: false,
  },
  {
    id: 9,
    title: "Modal",
    img: ["images/modal-lawyer/2022-03-22 (31).png"],
    features: ["React", "CSS", "Hooks"],
    url: "https://modal-input.vercel.app/",
    github: "https://github.com/JohnKucharsky/modal-input",
    color: false,
  },
  {
    id: 10,
    title: "Router V6",
    img: [
      "images/ninja-router/2022-03-22 (8).png",
      "images/ninja-router/2022-03-22 (9).png",
      "images/ninja-router/2022-03-22 (10).png",
      "images/ninja-router/2022-03-22 (11).png",
    ],
    features: ["React", "RouterV6"],
    url: "https://reactrouterv6.vercel.app/",
    github: "https://github.com/JohnKucharsky/reactrouterv6",
    color: false,
  },
  {
    id: 11,
    title: "Redux Shopping Cart",
    img: ["images/redux-ind-fire/2022-03-22 (23).png"],
    features: ["React", "Redux", "Firebase"],
    url: "https://redux-ind-fire.vercel.app/",
    github: "https://github.com/JohnKucharsky/Redux-Ind-Fire",
    color: false,
  },
  {
    id: 12,
    title: "Typescript ToDo List",
    img: ["images/todo-typescript/2022-03-22 (36).png"],
    features: ["React", "Typescript"],
    url: "https://todoapp-typescript-amber.vercel.app/",
    github: "https://github.com/JohnKucharsky/todoapp-typescript",
    color: false,
  },
  {
    id: 13,
    title: "Breaking Bad",
    img: ["images/traversy-bb/2022-03-22 (6).png"],
    features: ["React", "API", "Search"],
    url: "https://traversy-bb.vercel.app/",
    github: "https://github.com/JohnKucharsky/traversy-bb",
    color: true,
  },
  {
    id: 14,
    title: "Typescript Shopping Cart",
    img: [
      "images/type-shoppingcart/2022-03-22 (28).png",
      "images/type-shoppingcart/2022-03-22 (29).png",
    ],
    features: ["React", "Typiscript", "MaterialUI", "StyledComponents", "API"],
    url: "https://typescript-shopping-cart-nine.vercel.app/",
    github: "https://github.com/JohnKucharsky/TypescriptShoppingCart",
    color: false,
  },
  {
    id: 15,
    title: "Movie Watchlist",
    img: ["images/watchlist-movie/2022-03-22 (21).png"],
    features: ["React", "ContextAPI", "TailwindCSS", "useReducer", "MovieAPI"],
    url: "https://watchlist-movies-sigma.vercel.app/",
    github: "https://github.com/JohnKucharsky/watchlist-movies",
    color: false,
  },
  {
    id: 16,
    title: "Gatsby Blog",
    img: [
      "images/web-warrior/2022-03-22 (18).png",
      "images/web-warrior/2022-03-22 (19).png",
      "images/web-warrior/2022-03-22 (20).png",
    ],
    features: ["Gatsby", "GraphQL"],
    url: "https://wizardly-hermann-0d2e3d.netlify.app/",
    github: "https://github.com/JohnKucharsky/gatsby-starter-hello-world",
    color: true,
  },
  {
    id: 17,
    title: "Recipe Spoonacular",
    img: [
      "images/spoonacular/2022-04-11 (13).png",
      "images/spoonacular/2022-04-11 (14).png",
      "images/spoonacular/2022-04-11 (15).png",
    ],
    features: [
      "React",
      "SASS",
      "Typescript",
      "API",
      "Search",
      "ReactRouter",
      "SplideJS",
      "FramerMotion",
    ],
    url: "https://spoonacular-typescript.vercel.app/",
    github: "https://github.com/JohnKucharsky/spoonacular-typescript",
    color: false,
  },
  {
    id: 18,
    title: "Paintings Gallery",
    img: [
      "images/paintings/2022-04-11 (1).png",
      "images/paintings/2022-04-11 (2).png",
      "images/paintings/2022-04-11.png",
    ],
    features: ["React", "Styled Components", "API", "Search"],
    url: "https://paintings-gallery.vercel.app/",
    github: "https://github.com/JohnKucharsky/paintings-gallery",
    color: false,
  },
  {
    id: 19,
    title: "Exceed",
    img: [
      "images/exceed/2022-04-11 (4).png",
      "images/exceed/2022-04-11 (5).png",
      "images/exceed/2022-04-11 (3).png",
    ],
    features: ["React", "Styled Components", "Mobile Responsive"],
    url: "https://exceed-theta.vercel.app/",
    github: "https://github.com/JohnKucharsky/exceed",
    color: false,
  },
];
