export const data = [
  {
    id: 1,
    title: "Breaking Bad",
    img: ["images/traversy-bb/2022-03-22 (6).png"],
    features: ["React", "API", "Search"],
    url: "https://traversy-bb.vercel.app/",
    github: "https://github.com/JohnKucharsky/traversy-bb",
    color: true,
  },
  {
    id: 2,
    title: "CSS Grid",
    img: ["images/grid/2022-04-11 (6).png"],
    features: ["HTML", "CSS", "Grid"],
    url: "https://cinet.vercel.app/",
    github: "https://github.com/JohnKucharsky/Cinet",
    color: false,
  },

  {
    id: 3,
    title: "Router V6",
    img: [
      "images/ninja-router/2022-03-22 (8).png",
      "images/ninja-router/2022-03-22 (9).png",
      "images/ninja-router/2022-03-22 (10).png",
      "images/ninja-router/2022-03-22 (11).png",
    ],
    features: ["React", "RouterV6"],
    url: "https://reactrouterv6.vercel.app/",
    github: "https://github.com/JohnKucharsky/reactrouterv6",
    color: false,
  },
  {
    id: 5,
    title: "Modal S",
    img: ["images/modal-lawyer/2022-03-22 (31).png"],
    features: ["React", "CSS", "Hooks"],
    url: "https://modal-input.vercel.app/",
    github: "https://github.com/JohnKucharsky/modal-input",
    color: false,
  },

  {
    id: 6,
    title: "Pixabay API",
    img: ["images/gallery/2022-03-22 (24).png"],
    features: ["React", "API", "TailwindCSS"],
    url: "https://pixabay-gallery-psi.vercel.app/",
    github: "https://github.com/JohnKucharsky/Pixabay-Gallery",
    color: false,
  },
  {
    id: 8,
    title: "Gatsby Blog",
    img: [
      "images/web-warrior/2022-03-22 (18).png",
      "images/web-warrior/2022-03-22 (19).png",
      "images/web-warrior/2022-03-22 (20).png",
    ],
    features: ["Gatsby", "GraphQL"],
    url: "https://wizardly-hermann-0d2e3d.netlify.app/",
    github: "https://github.com/JohnKucharsky/gatsby-starter-hello-world",
    color: true,
  },

  {
    id: 9,
    title: "Modal",
    img: ["images/modal-travel/2022-05-05 (2).png"],
    features: ["React", "SASS", "Material UI"],
    url: "https://modal-brnl.vercel.app/",
    github: "https://github.com/JohnKucharsky/modal-brnl",
    color: false,
  },
  {
    id: 10,
    title: "Redux Shopping Cart",
    img: ["images/redux-ind-fire/2022-03-22 (23).png"],
    features: ["React", "Redux", "Firebase"],
    url: "https://redux-ind-fire.vercel.app/",
    github: "https://github.com/JohnKucharsky/Redux-Ind-Fire",
    color: false,
  },
  {
    id: 11,
    title: "Typescript ToDo List",
    img: ["images/todo-typescript/2022-03-22 (36).png"],
    features: ["React", "Typescript"],
    url: "https://todoapp-typescript-amber.vercel.app/",
    github: "https://github.com/JohnKucharsky/todoapp-typescript",
    color: false,
  },

  {
    id: 13,
    title: "Portfolio",
    img: [
      "images/egator-portfolio/2022-03-22 (37).png",
      "images/egator-portfolio/2022-03-22 (38).png",
      "images/egator-portfolio/2022-03-22 (39).png",
      "images/egator-portfolio/2022-03-22 (40).png",
      "images/egator-portfolio/2022-03-22 (41).png",
      "images/egator-portfolio/2022-03-22 (42).png",
    ],
    features: ["React", "CSS", "Animation"],
    url: "https://egator.vercel.app/",
    github: "https://github.com/JohnKucharsky/egator",
    color: true,
  },
  {
    id: 14,
    title: "Calculator Modal",
    img: ["images/calc-redux/2022-03-22 (30).png"],
    features: ["React", "ReduxToolkit", "Firebase"],
    url: "https://calcredux-ashen.vercel.app/",
    github: "https://github.com/JohnKucharsky/calcredux",
    color: false,
  },
  {
    id: 15,
    title: "Bootstrap",
    img: [
      "images/bootstrap-ninja/2022-03-22 (1).png",
      "images/bootstrap-ninja/2022-03-22 (2).png",
      "images/bootstrap-ninja/2022-03-22 (3).png",
      "images/bootstrap-ninja/2022-03-22 (4).png",
      "images/bootstrap-ninja/2022-03-22 (5).png",
    ],
    features: ["Bootstrap", "HTML", "CSS"],
    url: "https://bootstrap5-02.vercel.app/",
    github: "https://github.com/JohnKucharsky/Bootstrap5-02",
    color: false,
  },
  {
    id: 16,
    title: "Table random",
    img: ["images/table/2022-05-05.png"],
    features: ["React", "Styled Components", "API", "Search"],
    url: "https://table-psi.vercel.app/",
    github: "https://github.com/JohnKucharsky/table",
    color: true,
  },

  {
    id: 17,
    title: "Quiz Game",
    img: ["images/quiz-game/2022-05-05 (1).png"],
    features: ["React", "Typescript", "SASS", "Api"],
    url: "https://quiz-game-ts-sass.vercel.app/",
    github: "https://github.com/JohnKucharsky/quiz-game-ts-sass",
    color: true,
  },
  {
    id: 18,
    title: "Magic Memory",
    img: ["images/magic-memory/2022-04-11 (10).png"],
    features: ["React", "Javascript"],
    url: "https://magic-memory-zeta.vercel.app/",
    github: "https://github.com/JohnKucharsky/magic-memory",
    color: true,
  },
  {
    id: 19,
    title: "Tables",
    img: ["images/tables/2022-04-11 (12).png"],
    features: ["React", "Typescript", "SASS"],
    url: "https://sass-ts-versiontwo.vercel.app/",
    github: "https://github.com/JohnKucharsky/random-tables-sass-ts",
    color: false,
  },
  {
    id: 20,
    title: "Recipe Spoonacular",
    img: [
      "images/spoonacular/2022-04-11 (13).png",
      "images/spoonacular/2022-04-11 (14).png",
      "images/spoonacular/2022-04-11 (15).png",
    ],
    features: [
      "React",
      "SASS",
      "Typescript",
      "API",
      "Search",
      "ReactRouter",
      "SplideJS",
      "FramerMotion",
    ],
    url: "https://spoonacular-typescript.vercel.app/",
    github: "https://github.com/JohnKucharsky/spoonacular-typescript",
    color: false,
  },

  {
    id: 23,
    title: "Shopping Cart",
    img: [
      "images/shopping-cart-sass/2022-04-19 (1).png",
      "images/shopping-cart-sass/2022-04-19 (2).png",
      "images/shopping-cart-sass/2022-04-19 (4).png",
    ],
    features: ["React", "SASS", "Mobile Responsive", "Api", "useRef"],
    url: "https://adidas-eight.vercel.app/",
    github: "https://github.com/JohnKucharsky/adidas",
    color: false,
  },
  {
    id: 24,
    title: "Госуслуги",
    img: [
      "images/gosuslugi/2022-04-19 (5).png",
      "images/gosuslugi/2022-04-19 (6).png",
      "images/gosuslugi/2022-04-19 (7).png",
      "images/gosuslugi/2022-04-19 (8).png",
      "images/gosuslugi/2022-04-19 (9).png",
      "images/gosuslugi/2022-04-19 (10).png",
    ],
    features: ["React", "SASS", "Mobile Responsive"],
    url: "https://gosuslugi-two.vercel.app/",
    github: "https://github.com/JohnKucharsky/gosuslugi",
    color: false,
  },
];
